print('10/07/2023')
print('To my future me:')
print(' ')
print('Today I feel energized, fresh, and a new person.')
print("There are many things changing faster in my life,") 
print("I'm scared but also pretty excited")
print(' ')
print("I want to learn with this python's course to use this language and try")
print("and understand the way it works and how to do amazing things to future projects.")
print(' ')
print("Never stop doing things with your heart. It's hard, no one said it wasn't going to be,")
print("just keep your head up. YOU ARE WORTH IT.")
print("\u2620\uFE0F")